### ISSUE TITLE
Add support for metadata when sending funds or tokens

### ISSUE THREAD

**Issue by gocedoko** [Emurgo/yoroi-mobile#1237]
Quite important yet presumably simple to implement feature, allowing to send metadata to a transaction.

![image](https://user-images.githubusercontent.com/11044633/109718544-c6344000-7ba7-11eb-9076-4d06e6111738.png)

Is it already planned to implement this?

**Comment by SebastienGllmt** [comment]
The reason we haven't implemented this is because metadata isn't just a string -- it's structured data. That means we would have to ask the user to either put in JSON or put in some encoded hex string. Both of these are extremely error prone so I would strongly prefer not to do it.

There are two ways we want to tackle this problem:
1) By finished the Cardano connector (which allows dapps to talk to Yoroi) so that dapps can construct the specific metadata format required for whatever they need
2) Manually create UI for CIPs that require metadata. For example, our "voting" tab is an entire flow just to submit the Catalyst metadata transaction. If there are other standards we want to support, we would manually integrate them as well

One thing that could be kind of cool is a way to automatically generate the dialogs required for a metadata specification based on a CDDL specification, but I feel this could be a lot of work with few cases where this actually works and would rather people just use dapps through the connector.

**Comment by maurovz** [comment]
@SebastienGllmt I found this post by searching "dapp". Is this dapp connector functionality already implemented? I would love to add it to my connector Swift package.

**Comment by zuzunker** [comment]
> @SebastienGllmt I found this post by searching "dapp". Is this dapp connector functionality already implemented? I would love to add it to my connector Swift package.

@maurovz , the dapp-connector is a part of the Yoroi browser extension and is available for some time now. Not related to the Yoroi mobile project.

**Comment by maurovz** [comment]
Thanks for the quick reply. What I was trying to ask is, is it possible to do this connection with the mobile app? Similarly to this: 
![68747470733a2f2f692e696d6775722e636f6d2f36536547357a322e676966](https://user-images.githubusercontent.com/1994477/186466569-42337f5c-0709-43fb-9717-77f29510024c.gif)

**Comment by zuzunker** [comment]
> is it possible to do this connection with the mobile app?

Not yet
