### ISSUE TITLE
[Android] 'Use other login method' crashes application

### ISSUE THREAD

**Issue by joeltoby** [Emurgo/yoroi-mobile#1807]
### Description / affected users

This bug appears to affect Android users with biometric login enabled.  Attempting to login using the unlock PIN crashes the app.

### Bug reproduction constituency:

I am able to consistently reproduce this bug on my device.  My device info is included below.  PIN sign in never works for me.

### Steps to reproduce:

1. Enable biometric sign in (`Settings -> Application -> Sign in with biometrics`)
2. Exit the application
3. Open the application again
4. User is presented with the the 'Authorise with your biometrics' screen.  Click 'cancel' on this screen
5. User will then see a 'Use other login method' button.  Click this button.
6. User is again presented with the the 'Authorise with your biometrics' screen, but instead of a 'cancel' button, there is now a 'Use PIN' button.  Click this button. 
7. User is presented with the UI to enter their PIN ("Re-enter your PIN - Authorize operation").  Enter your PIN.
8. **Application crashes**

### Other info:

**My device:**  Google Pixel 5
**Android version:** 12
**Yoroi application version:** `4.4.1` (commit `bb929b71`)

Please let me know if you need any further info,

**Comment by stackchain** [comment]
Hi @joeltoby, thank you for the detailed description, yes, Android 12 is not supposed to be supported, it is enabled right now due to the way the SDK list is working. It is a blocked list, so if a new SDK is launched by default it'd be enabled, we have to change that. Yet, we will be migrating from our in-house keystore to react-keychain package soon.

**Comment by stackchain** [comment]
Fixed in `4.9.0`
