### ISSUE TITLE
Application is losing current state if locked

### ISSUE THREAD

**Issue by PavelHaliakevich** [Emurgo/yoroi-mobile#588]
Steps to reproduce:
1. Click "restore wallet" button on the main page
2. Enter the correct recovery phrase and click "Restore wallet"
3. Lock the phone and wait >30 seconds
4. Unlock the phone, click "Login" and enter the PIN

Expected result: The application opens on the page where you left.
Actual result: The application opens on the "Your wallets" page.

**Comment by MichalPetro** [comment]
It may be non-trivial to remember and restore the state on some screens so we would be forced to move user back to the last screen where it is safe to restore the state (for example if you lock and return on send transaction confirmation screen we would have to move the user to blank or pre-filled send screen. Or another example - lock and return to new wallet creation or wallet restore may pose a serious risk if we are unable to restore the state correctly - therefore we rather move the user to select wallet screen also if it is blank with no wallet created yet so the user can start over with wallet creation/restore)

Therefore we made this UX vs effort compromise.

But actually, if you think this is uncomfortable from a user perspective you can increase the lock-out timer to 60 seconds because this "state reset" is triggered only when the user is locked out.

**Comment by nicarq** [comment]
@MichalPetro shouldn’t the lock screen be a modal screen on top of whatever is under it? if the user successfully authenticates, the modal screen would be dismissed and whatever was under would be shown.

**Comment by MichalPetro** [comment]
@nicarq current implementation: lock out = log off

lockout screen as modal would be nice to have but very difficult to implement due to many implications.

too many authorization options, some of them using our screens some of the using system screens
if we wanted to implement this we would have to clear too many exceptions

we suggest leaving this as it is or if you think 30 seconds timeout is too short, make it 60.

**Comment by nicarq** [comment]
@MichalPetro aha I see. I need to think...

**Comment by PavelHaliakevich** [comment]
Moved to Clubhouse
https://app.clubhouse.io/emurgo/story/1781/android-ios-application-is-losing-current-state-if-locked

**Comment by nicarq** [comment]
@PavelHaliakevich thanks! I will comment there
