### ISSUE TITLE
Yoroi app for Apple - text cuts off in buttons

### ISSUE THREAD

**Issue by KarynaSovich** [Emurgo/yoroi-mobile#607]
Hello!

In Yoroi mobile app for Apple
- text in buttons cuts off or isn't filled completely with color
- title of the date doesn't appear completely ( we can't change format of it ourselves in settings)
- in Send menu, a line which shows tx details also cuts off

Please, take a look at pics attached below.
I have made screens in Russian version of app but the same issues appear in other languages too.

Thank you! 

![img_8675](https://user-images.githubusercontent.com/44111743/51442691-e49c9180-1ce7-11e9-9c82-a471bfee94e3.PNG)
![img_8669](https://user-images.githubusercontent.com/44111743/51442693-e6feeb80-1ce7-11e9-9035-305e8fcdd5ec.PNG)
![img_8683](https://user-images.githubusercontent.com/44111743/51442694-e8c8af00-1ce7-11e9-8b71-97947bfb8940.PNG)
![img_8684](https://user-images.githubusercontent.com/44111743/51442697-eb2b0900-1ce7-11e9-9adf-13d625e7e8a2.PNG)
![img_8676](https://user-images.githubusercontent.com/44111743/51442698-ecf4cc80-1ce7-11e9-8ae9-ab1ec7177b38.PNG)

**Comment by MichalPetro** [comment]
Hello @KarynaSovich, what phone and what ios version are you using? 

I just tested on iphone 5s (I think the display is the same as iphone SE) and noticed all the issues. These are issues related to small display resolution and different translation text lengths. I will have to check with our FE styling guy but he is on vacation this week.

Date in Russian format - this has to be either resolved by text shrinking or by changing the format of the date. The same happens also in the English version. I suggest date format change and use unified or very similar date format for all languages

Transaction ID - It was intentional not to display the whole TX ID as it is too long but on higher resolutions we leave a border on the right side so it is not obvious. 
If we want to fit the whole transaction ID text there we either have to put dots ... in the middle of text, in the end of the text, or completely change the format of how this text is displayed

"You have to use some of your addresses" button text - resolution issue, we need to auto-shrink the text to fit for small resolution but the text may become unreadable than...

The rest (assurance level buttons, fee & ada received text overflow) seems to be a combination of small resolution and length of the text in a different language. I really dont know what we can do because shrinking the text is out of question as it will be too small to read
