### ISSUE TITLE
(Android) Authorize Via Fingerprint Fails To Trigger If Screen Locks On Page

### ISSUE THREAD

**Issue by robkorn** [Emurgo/yoroi-mobile#637]
In short, if you lock your screen on the fingerprint page, then it doesn't seem to check for your fingerprint when the phone is unlocked again. This was found on an LG G5.

Steps to reproduce:
1. Get to the "Authorize with your fingerprint" page
2. Lock Screen
3. Unlock
4. Fingerprint Authorization no longer works.

**Comment by PavelHaliakevich** [comment]
Confirmed on Huawei p20

**Comment by Sami32** [comment]
After reading your comment i get suspicious about my fingerprint issue with my Xiaomi  smartphone (Android 7.0)
I've always thought that the fact that fingerprint logging never worked and defaulted on the pattern mode was due to Android 7.0, and i was worried about Cerberus RAT attacks!

But you gave me the idea to disable my smartphone fingerprint lock and then reenable it and register my fingerprint a new time then...Yoroi App fingerprint logging mode finally worked!

Thank you for your help ;)

EDIT:
Perhaps it came from the fact that i had 2 fingerprints registred and Yoroi doesn't handle it correctly?
I don't know if it is your case.
